### ISSUE TITLE
Stuck at SwitchAai login redirect?

### ISSUE THREAD

**Issue by lthiet** [jstiefel/asvz_bot#3]
Hello.

Just wanted to know if this behaviour happens on your end as well. The driver get stuck in the redirect website of SwitchAai. 

If yes then I'm working on a fix.

**Comment by lthiet** [comment]
hey so turns out i'm just stupid. didn't have the right password

**Comment by jstiefel** [comment]
I really had this behaviour before even with a right PW. Got stuck on the blank page where the redirect should happen.

**Comment by lthiet** [comment]
weird, i will let you know if i encounter the same problem
